from typing import List, Tuple

import torch

# This module extends the tokenizer with Phase-1 latent action tokens and answer control token,
# resizes model embeddings accordingly, validates assumptions, and applies embedding-level freezing.


def build_phase1_tokens(z_vocab_size: int = 64, answer_token: str = "</answer>") -> Tuple[List[str], str]:
    """Return explicit z-token strings and the answer token string.

    Tokens are explicit, not generated by regex at runtime.
    """
    if z_vocab_size != 64:
        raise ValueError("Phase-1 requires z_vocab_size=64 exactly.")
    z_tokens = [f"<z{i}>" for i in range(z_vocab_size)]
    return z_tokens, answer_token


def _add_special_tokens(tokenizer, z_tokens: List[str], answer_token: str) -> None:
    # Register all tokens as special to ensure they are atomic and never split
    special_set = list(z_tokens) + [answer_token]
    added = tokenizer.add_special_tokens({"additional_special_tokens": special_set})
    # Note: if some tokens already exist, added may be < len(special_set)
    print(f"Added {added} new special tokens (requested {len(special_set)}).")


def _validate_digits_atomic(tokenizer) -> None:
    # Ensure each digit maps to exactly one token id
    for d in [str(i) for i in range(10)]:
        ids = tokenizer.encode(d, add_special_tokens=False)
        if len(ids) != 1:
            raise ValueError(f"Digit token '{d}' is not atomic; got ids {ids}.")
    print("Digit token validation passed: '0'..'9' are atomic.")


def _get_token_ids(tokenizer, tokens: List[str]) -> List[int]:
    ids = tokenizer.convert_tokens_to_ids(tokens)
    if any(i is None for i in ids):
        missing = [t for t, i in zip(tokens, ids) if i is None]
        raise ValueError(f"Some special tokens have no ids: {missing}")
    return ids


def _validate_contiguous(ids: List[int]) -> Tuple[int, int]:
    s = sorted(ids)
    min_id, max_id = s[0], s[-1]
    expected = max_id - min_id + 1
    if expected != len(ids):
        raise ValueError(
            f"z-token ids are not contiguous: range [{min_id},{max_id}] vs count {len(ids)} (sorted={s})."
        )
    print(f"z-token ids contiguous: range [{min_id},{max_id}]")
    return min_id, max_id


def _apply_embedding_freeze(model, tokenizer, z_token_ids: List[int], answer_token_id: int) -> None:
    # Only <z*> embeddings are trainable; all others frozen. </answer> is frozen.
    emb = model.get_input_embeddings()
    if emb is None:
        raise ValueError("Model does not expose input embeddings via get_input_embeddings().")

    weight = emb.weight
    vocab_size = weight.shape[0]

    # Build mask: 1 for z-token rows, 0 otherwise (including answer token)
    mask = torch.zeros(vocab_size, dtype=weight.dtype)
    model.register_buffer("_z_grad_mask", mask)

    for i in z_token_ids:
        if not (0 <= i < vocab_size):
            raise ValueError(f"z-token id {i} out of embedding range 0..{vocab_size-1}")
        mask[i] = 1.0
    # Ensure answer token is frozen
    if 0 <= answer_token_id < vocab_size:
        mask[answer_token_id] = 0.0

    # Require gradients on embedding weights, then mask them via a gradient hook
    weight.requires_grad_(True)

    def grad_mask_hook(grad):
        mask = model._z_grad_mask.to(grad.device)
        return grad * mask.unsqueeze(1)

    # Remove existing hooks if any to avoid stacking
    if hasattr(weight, "_lmms_grad_hook") and weight._lmms_grad_hook is not None:
        weight._lmms_grad_hook.remove()
    hook = weight.register_hook(grad_mask_hook)
    # Track hook on the tensor for potential future cleanup
    weight._lmms_grad_hook = hook  # type: ignore[attr-defined]

    # Sanity check: simulate a ones grad and assert rows
    with torch.no_grad():
        test = torch.ones_like(weight)
        masked = grad_mask_hook(test)
        # All z rows should be non-zero; others zero
        non_z = set(range(vocab_size)) - set(z_token_ids)
        if masked[z_token_ids].abs().sum() == 0:
            raise RuntimeError("Gradient mask failed: z-token rows became zero.")
        if masked[list(non_z)].abs().sum() != 0:
            raise RuntimeError("Gradient mask failed: non z-token rows are not zero.")
    print("Embedding freezing applied: only <z*> rows trainable; </answer> frozen.")


def extend_tokenizer_and_resize(model, tokenizer, z_vocab_size: int = 64, answer_token: str = "</answer>"):
    """
    Extend tokenizer with <z0>..<z63> and </answer>, resize model embeddings/LM head,
    validate Phase-1 assumptions, and apply embedding-level freezing so only z-token
    rows are trainable.
    """
    # Build tokens
    z_tokens, ans_tok = build_phase1_tokens(z_vocab_size=z_vocab_size, answer_token=answer_token)

    # Add special tokens
    _add_special_tokens(tokenizer, z_tokens, ans_tok)

    # Resize model embeddings (and tied lm head if applicable)
    new_vocab_size = len(tokenizer)
    model.resize_token_embeddings(new_vocab_size)
    print(f"Resized model embeddings to vocab size {new_vocab_size}.")

    # Validations
    _validate_digits_atomic(tokenizer)
    z_ids = _get_token_ids(tokenizer, z_tokens)
    ans_id = tokenizer.convert_tokens_to_ids(ans_tok)
    if ans_id is None:
        raise ValueError("</answer> did not get a valid token id.")
    z_min, z_max = _validate_contiguous(z_ids)

    # Apply embedding-level freeze rules
    _apply_embedding_freeze(model, tokenizer, z_ids, ans_id)

    # Final log summary
    print(
        f"Tokenizer extension complete: added {len(z_tokens)+1} tokens; z-token id range [{z_min},{z_max}]; answer_token_id={ans_id}."
    )


__all__ = [
    "extend_tokenizer_and_resize",
    "build_phase1_tokens",
]
