from typing import List, Tuple

import torch

# This module extends the tokenizer with Phase-1 latent action tokens and answer control token,
# resizes model embeddings accordingly, validates assumptions, and applies embedding-level freezing.


def build_phase1_tokens(z_vocab_size: int = 64, answer_token: str = "</answer>") -> Tuple[List[str], str]:
    """Return explicit z-token strings and the answer token string.

    Tokens are explicit, not generated by regex at runtime.
    """
    if z_vocab_size != 64:
        raise ValueError("Phase-1 requires z_vocab_size=64 exactly.")
    z_tokens = [f"<z{i}>" for i in range(z_vocab_size)]
    return z_tokens, answer_token


def _add_special_tokens(tokenizer, z_tokens: List[str], answer_token: str) -> None:
    # Register all tokens as special to ensure <z*> and </answer> tokens are atomic and never split
    special_set = list(z_tokens) + [answer_token]
    added = tokenizer.add_special_tokens({"additional_special_tokens": special_set})
    # Note: if some tokens already exist, added may be < len(special_set)
    print(f"Added {added} new special tokens (requested {len(special_set)}).")

def _get_token_ids(tokenizer, tokens: List[str]) -> List[int]:
    ids = tokenizer.convert_tokens_to_ids(tokens)
    if any(i is None for i in ids):
        missing = [t for t, i in zip(tokens, ids) if i is None]
        raise ValueError(f"Some special tokens have no ids: {missing}")
    return ids


def _validate_contiguous(ids: List[int]) -> Tuple[int, int]:
    s = sorted(ids)
    min_id, max_id = s[0], s[-1]
    expected = max_id - min_id + 1
    if expected != len(ids):
        raise ValueError(
            f"z-token ids are not contiguous: range [{min_id},{max_id}] vs count {len(ids)} (sorted={s})."
        )
    print(f"z-token ids contiguous: range [{min_id},{max_id}]")
    return min_id, max_id

def _apply_embedding_freeze(
    model,
    z_token_ids: List[int],
    answer_token_id: int,
) -> None:
    """
    Apply embedding-level gradient masking so that:
      - <z*> token embeddings are trainable
      - </answer> token embedding is trainable
      - all other token embeddings are frozen

    This is implemented via a gradient hook on the embedding matrix.
    """

    emb = model.get_input_embeddings()
    if emb is None:
        raise ValueError("Model does not expose input embeddings via get_input_embeddings().")

    weight = emb.weight
    vocab_size, hidden_dim = weight.shape

    # -------------------------------
    # Build gradient mask
    # -------------------------------
    # mask[i] == 1 → gradients allowed for token i
    # mask[i] == 0 → gradients blocked for token i
    mask = torch.zeros(vocab_size, dtype=weight.dtype)

    trainable_ids = set(z_token_ids)

    if 0 <= answer_token_id < vocab_size:
        trainable_ids.add(answer_token_id)
    else:
        raise ValueError(f"answer_token_id {answer_token_id} out of embedding range")

    for i in trainable_ids:
        if not (0 <= i < vocab_size):
            raise ValueError(f"Trainable token id {i} out of embedding range 0..{vocab_size - 1}")
        mask[i] = 1.0

    # Register mask as a persistent buffer on the model
    model.register_buffer("_lmms_embedding_grad_mask", mask)

    # -------------------------------
    # Enable gradients + attach hook
    # -------------------------------
    weight.requires_grad_(True)

    def grad_mask_hook(grad: torch.Tensor) -> torch.Tensor:
        """
        grad: [vocab_size, hidden_dim]
        """
        m = model._lmms_embedding_grad_mask.to(grad.device)
        return grad * m.unsqueeze(1)

    # Remove existing hook to avoid stacking
    if hasattr(weight, "_lmms_grad_hook") and weight._lmms_grad_hook is not None:
        weight._lmms_grad_hook.remove()

    hook = weight.register_hook(grad_mask_hook)
    weight._lmms_grad_hook = hook  # type: ignore[attr-defined]

    # -------------------------------
    # Sanity check
    # -------------------------------
    with torch.no_grad():
        test_grad = torch.ones_like(weight)
        masked = grad_mask_hook(test_grad)

        non_trainable_ids = set(range(vocab_size)) - trainable_ids

        if masked[list(trainable_ids)].abs().sum() == 0:
            raise RuntimeError("Gradient mask failure: trainable rows became zero.")

        if non_trainable_ids and masked[list(non_trainable_ids)].abs().sum() != 0:
            raise RuntimeError("Gradient mask failure: frozen rows received gradients.")

    print(
        f"Embedding freeze applied: "
        f"{len(z_token_ids)} <z*> tokens + </answer> are trainable; "
        f"{vocab_size - len(trainable_ids)} tokens frozen."
    )

def extend_tokenizer_and_resize(model, tokenizer, z_vocab_size: int = 64, answer_token: str = "</answer>"):
    """
    Extend tokenizer with <z0>..<z63> and </answer>, resize model embeddings/LM head,
    validate Phase-1 assumptions,  apply embedding-level freezing so <z*> tokens and </answer> are trainable.
    """
    # Build tokens
    z_tokens, ans_tok = build_phase1_tokens(z_vocab_size=z_vocab_size, answer_token=answer_token)

    # Add special tokens
    _add_special_tokens(tokenizer, z_tokens, ans_tok)

    # Resize model embeddings (and tied lm head if applicable)
    new_vocab_size = len(tokenizer)
    model.resize_token_embeddings(new_vocab_size)
    print(f"Resized model embeddings to vocab size {new_vocab_size}.")

    # Validations
    z_ids = _get_token_ids(tokenizer, z_tokens)
    ans_id = tokenizer.convert_tokens_to_ids(ans_tok)
    if ans_id is None:
        raise ValueError("</answer> did not get a valid token id.")
    z_min, z_max = _validate_contiguous(z_ids)

    # Apply embedding-level freeze rules
    _apply_embedding_freeze(model, z_ids, ans_id)

    # Final log summary
    print(
        f"Tokenizer extension complete: added {len(z_tokens)+1} tokens; z-token id range [{z_min},{z_max}]; answer_token_id={ans_id}."
    )


__all__ = [
    "extend_tokenizer_and_resize",
    "build_phase1_tokens",
]
