# ─────────────────────────────────────────────────────────────
# Model
# ─────────────────────────────────────────────────────────────
model:
  name: Qwen/Qwen2.5-Math-1.5B-Instruct
  answer_token: "<ANSWER>"

# ─────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────
dataset:
  hf_name: omrisap/generated-math-phase0   # HF dataset path
  split: train
  max_length: 512

# ─────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────
training:
  batch_size: 32
  epochs: 3
  lr: 3.0e-4

  # Unfreeze top X% of transformer layers
  # 0.0 = only <ANSWER> embedding + heads
  # 0.25 ≈ top 25% layers
  unfrozen_layer_pct: 0.25

  gradient_clip: 1.0

# ─────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────
logging:
  log_every: 50

# ─────────────────────────────────────────────────────────────
# Output
# ─────────────────────────────────────────────────────────────
output_dir: phase0_ckpt
